name: Run Python Cleaning

on:
  workflow_dispatch:
    schedule:
    - cron: '30 1 * * *'

permissions:
  contents: write    

jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
      - name: Get repository files
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install pandas
        run: pip install pandas

      - name: Run Python script
        run: python test_automation.py
      - name: Save cleaned data to repository
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add cleaned_data.csv
          git diff --cached --quiet || git commit -m "Update cleaned data"
          git push
